name: algorithms-and-data-structures

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'algorithms-and-data-structures/**'
      - '!algorithms-and-data-structures/**/*.md'
      - '!algorithms-and-data-structures/.gitignore'
      - '!algorithms-and-data-structures/LICENSE'
  pull_request:
    branches:
      - main
    paths:
      - 'algorithms-and-data-structures/**'
      - '!algorithms-and-data-structures/**/*.md'
      - '!algorithms-and-data-structures/.gitignore'
      - '!algorithms-and-data-structures/LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradle in algorithms-and-data-structures
        run: chmod +x gradlew
        working-directory: ./algorithms-and-data-structures

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            algorithms-and-data-structures/.gradle/caches
            algorithms-and-data-structures/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('algorithms-and-data-structures/**/gradle*.kts', 'algorithms-and-data-structures/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle in algorithms-and-data-structures
        run: ./gradlew build
        working-directory: ./algorithms-and-data-structures

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradle in algorithms-and-data-structures
        run: chmod +x gradlew
        working-directory: ./algorithms-and-data-structures

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            algorithms-and-data-structures/.gradle/caches
            algorithms-and-data-structures/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('algorithms-and-data-structures/**/gradle*.kts', 'algorithms-and-data-structures/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Test with Gradle in algorithms-and-data-structures
        run: ./gradlew test
        working-directory: ./algorithms-and-data-structures