name: spring-security-in-action

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'algorithms-data-structs/**'
      - '!algorithms-data-structs/**/*.md'
      - '!algorithms-data-structs/.gitignore'
      - '!algorithms-data-structs/LICENSE'
  pull_request:
    branches:
      - main
    paths:
      - 'algorithms-data-structs/**'
      - '!algorithms-data-structs/**/*.md'
      - '!algorithms-data-structs/.gitignore'
      - '!algorithms-data-structs/LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradle in algorithms-data-structs
        run: chmod +x gradlew
        working-directory: ./algorithms-data-structs

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            algorithms-data-structs/.gradle/caches
            algorithms-data-structs/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('algorithms-data-structs/**/gradle*.kts', 'algorithms-data-structs/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle in algorithms-data-structs
        run: ./gradlew build
        working-directory: ./algorithms-data-structs

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradle in algorithms-data-structs
        run: chmod +x gradlew
        working-directory: ./algorithms-data-structs

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            algorithms-data-structs/.gradle/caches
            algorithms-data-structs/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('algorithms-data-structs/**/gradle*.kts', 'algorithms-data-structs/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Test with Gradle in algorithms-data-structs
        run: ./gradlew test
        working-directory: ./algorithms-data-structs