name: spring-security-in-action

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'spring/security/security-demo/**'
      - '!spring/security/security-demo/**/*.md'
      - '!spring/security/security-demo/.gitignore'
      - '!spring/security/security-demo/LICENSE'
  pull_request:
    branches:
      - main
    paths:
      - 'spring/security/security-demo/**'
      - '!spring/security/security-demo/**/*.md'
      - '!spring/security/security-demo/.gitignore'
      - '!spring/security/security-demo/LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradle in spring/security/security-demo
        run: chmod +x gradlew
        working-directory: ./spring/security/security-demo

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            spring/security/security-demo/.gradle/caches
            spring/security/security-demo/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('spring/security/security-demo/**/gradle*.kts', 'spring/security/security-demo/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle in spring/security/security-demo
        run: ./gradlew build
        working-directory: ./spring/security/security-demo

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradle in spring/security/security-demo
        run: chmod +x gradlew
        working-directory: ./spring/security/security-demo

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            spring/security/security-demo/.gradle/caches
            spring/security/security-demo/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('spring/security/security-demo/**/gradle*.kts', 'spring/security/security-demo/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Test with Gradle in spring/security/security-demo
        run: ./gradlew test
        working-directory: ./spring/security/security-demo